---
- name: Get crumb token
  uri:
    url: "{{ jenkins_url }}/crumbIssuer/api/json"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
  register: get_crumb_token_cmd
  when: jenkins_csrf_enabled == 'true'

- set_fact:
    headers:
    - key: "{{ get_crumb_token_cmd.json.crumbRequestField }}"
      value: "{{ get_crumb_token_cmd.json.crumb }}"
  when: jenkins_csrf_enabled == 'true'

- set_fact:
    headers: []
  when: jenkins_csrf_enabled == 'false'

- name: Create Username/Password Credentials
  include_tasks: _create_credentials.yaml
  vars:
    req_headers: "{{ headers }}"
    credential: "{{ user_pass_credential }}"
    type: "user_pass"
  with_dict: "{{ jenkins_user_pass_credentials }}"
  loop_control:
    loop_var: user_pass_credential

- name: Create SSH username with private key credentials
  include_tasks: _create_credentials.yaml
  vars:
    req_headers: "{{ headers }}"
    credential: "{{ ssh_user_key_credential }}"
    type: "ssh_user_with_private_key"
  with_dict: "{{ jenkins_ssh_user_key_credentials }}"
  loop_control:
    loop_var: ssh_user_key_credential

- name: Create secret text credentials
  include_tasks: _create_credentials.yaml
  vars:
    req_headers: "{{ headers }}"
    credential: "{{ secret_text_credential }}"
    type: "secret_text"
  with_dict: "{{ jenkins_secret_text_credentials }}"
  loop_control:
    loop_var: secret_text_credential

- name: Create aws credentials
  include_tasks: _create_credentials.yaml
  vars:
    req_headers: "{{ headers }}"
    credential: "{{ aws_credential }}"
    type: "aws_creds"
  with_dict: "{{ jenkins_aws_credentials }}"
  loop_control:
    loop_var: aws_credential