#!groovy
@Library('delorean-pipeline-library@registry-fns')

def registrySecret = params.registrySecret
def registryHost = params.registryHost
def registryImageName = params.registryImageName
def registryImageTag = params.registryImageTag
def expectError = params.expectError

stage('Registry Image Tag Validation') {
    def params = [
        credentials: registrySecret,
        host: registryHost,
        image: registryImageName,
        tag: registryImageTag
    ]
    def exists = registryHasImage(params)
    
    if (!exists && !expectError) {
        error "[ERROR] Image should exist: ${registryImageName}:${registryImageTag}"
    }

    if (exists && expectError) {
        error "[ERROR] Image should not exist: ${registryImageName}:${registryImageTag}"
    }
}
