#!groovy

def clusterOptions = [:]

def verifyClusterOptions(clusterOptions) {
    if (!clusterOptions.name || !clusterOptions.awsRegion || !clusterOptions.awsAccountName) {
        choiceAWSAccountName = new ChoiceParameterDefinition('awsAccountName', ['fheng'] as String[], 'AWS Account Name')
        def userInput = input message: 'Cluster Options', parameters: [
                string(defaultValue: (clusterOptions.name ?: ''), description: 'Cluster name', name: 'clusterName'),
                string(defaultValue: (clusterOptions.awsRegion ?: 'eu-west-2'), description: 'AWS Region', name: 'awsRegion'),
                choiceAWSAccountName
        ]
        clusterOptions.name = userInput.clusterName
        clusterOptions.awsRegion = userInput.awsRegion
        clusterOptions.awsAccountName = userInput.awsAccountName
        verifyClusterOptions(clusterOptions)
    }
}

stage("Cluster Options") {
    clusterOptions.name = params.clusterName
    clusterOptions.awsRegion = params.awsRegion
    clusterOptions.awsAccountName = params.awsAccountName
    verifyClusterOptions(clusterOptions)
    println "Cluster Options: ${clusterOptions}"
    currentBuild.displayName = "${currentBuild.displayName} ${clusterOptions.name}"
    currentBuild.description = "clusterName: ${clusterOptions.name}\nawsRegion: ${clusterOptions.awsRegion}"
}

node('cirhos_rhel7') {
    cleanWs()
    stage('Create OpenShift Cluster') {
        println("Create OpenShift Cluster")
        if (params.dryRun) {
            println("Would call ansibleTower with: oo_clusterid: ${clusterOptions.name}, oo_sublocation: ${clusterOptions.awsRegion}")
        } else {
            wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                ansibleTower(
                        towerServer: 'Dev Tower',
                        jobTemplate: 'Provision Cluster',
                        templateType: 'workflow',
                        importTowerLogs: true,
                        removeColor: false,
                        verbose: true,
                        extraVars: """---
                    oo_clusterid: ${clusterOptions.name}
                    oo_sublocation: ${clusterOptions.awsRegion}
                    cluster_credential_bundle_aws_name: ${clusterOptions.awsAccountName}
                    survey_provision_logging: 'false'"""
                )
            }
        }
    }
}
