#!groovy
timeout(240) { ansiColor('gnome-terminal') { timestamps {
    node('cirhos_rhel7') {
        stage ('Trigger OSD OCP4 Pipeline') {
            buildStatus = build(job: 'osd-ocp4-testing-executor', propagate: false, parameters: [
                string(name: 'CLUSTER_NAME', value: "${CLUSTER_NAME}"),
                string(name: 'RECIPIENTS', value: "${RECIPIENTS}"),
                string(name: 'INTEGREATLY_OPERATOR_BRANCH', value: "${INTEGREATLY_OPERATOR_BRANCH}"),
                string(name: 'TO_DO', value: "${TO_DO}")
            ]).result

            if (buildStatus == 'UNSTABLE') {
                currentBuild.result = 'UNSTABLE'
            } else if (buildStatus == 'SUCCESS') {
                currentBuild.result = 'SUCCESS'
            } else {
                currentBuild.result = 'FAILURE'
            }
        } // stage
    }// node
}}} // timeout, ansiColor, timestamps