#!groovy
Boolean isPds = params.PDS_CLUSTER

String clusterSuffix = isPds ? "cluster-${CLUSTER_NAME}.${CLUSTER_NAME}.${CLUSTER_DOMAIN}" : "${CLUSTER_NAME}.${CLUSTER_DOMAIN}"

String clusterAPI = "https://api.${clusterSuffix}:6443"

def err = null

node('cirhos_rhel7') {
    timeout(75) { ansiColor('gnome-terminal') { timestamps {
        try {
            currentBuild.displayName = "${currentBuild.displayName} ${CLUSTER_NAME}"
            stage('Login to OpenShift 4 cluster') {

                sh "oc login ${clusterAPI} --insecure-skip-tls-verify=true -u ${ADMIN_USERNAME} -p ${ADMIN_PASSWORD}"
            } // stage

            stage('Install RHMI') {
                dir('integreatly-operator') {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: INTEGREATLY_OPERATOR_BRANCH]],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [],
                        userRemoteConfigs: [[url: INTEGREATLY_OPERATOR_REPOSITORY]]
                    ])

                    sh "make test/e2e/olm"
                } // dir
            } // stage                 
        } catch (caughtError){
            currentBuild.result = 'FAILURE'
            err = caughtError
        } finally {
            notifyBuild(currentBuild.result, err)
        }
    }}} // timeout, ansiColor, timestamps
} // node

def notifyBuild(String buildStatus, err) {
    if (params.RECIPIENTS.toString().length() > 0) {
        buildStatus =  buildStatus ?: "SUCCESS"
    
        String mailRecipients = "${RECIPIENTS}"
        String subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
        String body = "${subject}\n\n(${env.BUILD_URL})"
    
        if (err != null) {
            body = "${body}\n\n FAILURE was ${err}"
        }
    
        mail body: body, subject: subject, to: mailRecipients   
    }
}